name: grun_chefapp
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  another_flushbar: ^1.12.30
  auto_size_text: ^3.0.0
  bitsdojo_window: ^0.1.5
  cached_network_image: ^3.2.3
  flutter_secure_storage: ^8.0.0
  http: ^0.13.5
  provider: ^6.0.5
  scrollable_positioned_list: ^0.3.7
  font_awesome_flutter: ^10.4.0
  socket_io_client: ^2.0.2
  simple_animations: ^5.0.0+3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.13.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/light_logo.png"
  adaptive_icon_background: "assets/dark_logo.png"
  windows:
    generate: true
    image_path: "assets/light_logo.png"
    icon_size: 48

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Paralucent
      fonts:
        - asset: fonts/paralucent.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat.ttf
        - asset: fonts/montserrat-regular.ttf
