name: grun_mobileapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_credit_card: ^3.0.6
  flutter_secure_storage: ^8.0.0
  font_awesome_flutter: ^10.4.0
  http: ^0.13.5
  marquee: ^2.2.3
  provider: ^6.0.5
  scrollable_positioned_list: ^0.3.7
  simple_animations: ^5.0.0+3
  socket_io_client: ^2.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "assets/light_logo.png"
  ios: true
  image_path: "assets/light_logo.png"
  adaptive_icon_background: "assets/dark_logo.png"
  windows:
    generate: true
    image_path: "assets/light_logo.png"
    icon_size: 48

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Paralucent
      fonts:
        - asset: fonts/paralucent.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat.ttf
        - asset: fonts/montserrat-regular.ttf
